balance_old_me_clear = ""
private_key = ""
randomness1 = ""
randomness2 = ""
value = ""

[balance_new_me_encrypted_1]
x = ""
y = ""

[balance_new_me_encrypted_2]
x = ""
y = ""

[balance_new_to_encrypted_1]
x = ""
y = ""

[balance_new_to_encrypted_2]
x = ""
y = ""

[balance_old_me_encrypted_1]
x = ""
y = ""

[balance_old_me_encrypted_2]
x = ""
y = ""

[public_key_me]
x = ""
y = ""

[public_key_to]
x = ""
y = ""
